# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop_yast_style.yml

# TODO: this need some non-trivial refactoring...
Metrics/AbcSize:
  Max: 111

# TODO: this need some non-trivial refactoring...
Metrics/BlockNesting:
  Max: 5

# TODO: this need some non-trivial refactoring...
Metrics/ClassLength:
  Max: 450

# TODO: this need some non-trivial refactoring...
Metrics/CyclomaticComplexity:
  Max: 25

Metrics/LineLength:
  Max: 100

# TODO: this need some non-trivial refactoring...
Metrics/MethodLength:
  Max: 96

# TODO: this need some non-trivial refactoring...
Metrics/PerceivedComplexity:
  Max: 25

# FIXME: It seems the cop does not handle this complex case correctly,
# disable it for now on that file.
Lint/ShadowedException:
  Exclude:
    - 'src/lib/registration/connect_helpers.rb'

# Offense count: 5
Style/AccessorMethodName:
  Enabled: false

# Offense count: 29
Style/Documentation:
  Enabled: false

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Let lslezak decide what to do with it. In general jreidinger does not see it as such big violence of style
Style/StructInheritance:
  Enabled: false
